name: mir-kiosk
version: 0.1
summary: A minimal Mir based shell for kiosk type applications
description: A minimal Mir based shell for kiosk type applications
confinement: strict
grade: devel

plugs:
  mir-libs:
    content: mir-libs
    interface: content
    target: mir-libs
    default-provider: mir-libs:mir-libs

apps:
  mir-kiosk:
    command: bin/run-miral
    daemon: simple
    slots: [mir]
    plugs: [opengl]

parts:
  miral-examples:
    plugin: nil
    stage-packages:
      - miral-examples

  icons:
    plugin: dump
    source: .
    stage-packages: [dmz-cursor-theme]
    organize:
      usr/share/icons/DMZ-White: icons/default

  glue:
    plugin: dump
    source: .
    organize:
      run-miral: bin/run-miral
      configure: meta/hooks/configure

  inotify-tools:
    plugin: nil
    stage-packages: [inotify-tools]
