name: mir-kiosk
adopt-info: mir-demos
summary: A minimal Mir based shell for kiosk type applications
description: A minimal Mir based shell for kiosk type applications
confinement: strict
base: core18

environment:
  #  # XDG config
  XDG_CONFIG_HOME: $SNAP_DATA
  XDG_RUNTIME_DIR: /run/user/0 # hardcoding as root for now
  # Prep for Mir
  MIR_CLIENT_PLATFORM_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/mir/client-platform
  MIR_SERVER_PLATFORM_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/mir/server-platform

layout:
  /usr/share:
    bind: $SNAP/usr/share
  /etc/glvnd:
    bind: $SNAP/etc/glvnd

apps:
  mir-kiosk:
    command: bin/run-miral
    daemon: simple
    slots:
      - mir
      - wayland
    plugs:
      - opengl

parts:
  ppa-mir:
    plugin: nil
    override-pull: |
      sudo apt --assume-yes install software-properties-common
      sudo add-apt-repository -yu ppa:mir-team/release
      snapcraftctl pull

  recipe-version:
    plugin: nil
    source: .
    source-type: git
    override-build: |
      git rev-list --count HEAD > $SNAPCRAFT_PART_INSTALL/recipe-version
    prime:
      - -recipe-version

  mir-demos:
    after: [ppa-mir, recipe-version]
    plugin: nil
    override-pull: |
      snapcraftctl pull
      mir_version=`LANG=C apt-cache policy mir-demos | sed -rne 's/^\s+Candidate:\s+([^-]*)-.+$/\1/p'`
      recipe_version=`cat $SNAPCRAFT_STAGE/recipe-version`
      snapcraftctl set-version $mir_version-snap$recipe_version
      if echo $mir_version | grep dev; then snapcraftctl set-grade devel; else snapcraftctl set-grade stable; fi
    stage-packages:
      - mir-graphics-drivers-desktop
      - mir-demos
      - libgl1-mesa-dri

  icons:
    plugin: nil
    stage-packages: [dmz-cursor-theme]

  glue:
    plugin: dump
    source: glue
