name: mir-kiosk
version: mir
version-script: |
    LANG=C apt-cache policy mir-demos | sed -rne 's/^\s+Candidate:\s+(.*)-[^-]+$/\1/p'
summary: A minimal Mir based shell for kiosk type applications
description: A minimal Mir based shell for kiosk type applications
confinement: strict
grade: stable
base: core18

environment:
  LC_ALL: C.UTF-8
  #  # XDG config
  XDG_CONFIG_HOME: $SNAP_DATA
  XDG_RUNTIME_DIR: /run/user/0 # hardcoding as root for now
  # Prep for Mir
  MIR_CLIENT_PLATFORM_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/mir/client-platform
  MIR_SERVER_PLATFORM_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/mir/server-platform

passthrough:
  layout:
    /usr/share:
      bind: $SNAP/usr/share
    /etc/glvnd:
      bind: $SNAP/etc/glvnd

apps:
  mir-kiosk:
    command: bin/run-miral
    daemon: simple
    slots:
      - mir
      - wayland
    plugs:
      - opengl

parts:
  ppa-mir-release:
    plugin: nil
    override-pull: |
      sudo apt --assume-yes install software-properties-common
      sudo add-apt-repository -yu ppa:mir-team/release
      # We shouldn't need to install stuff here, but it seems to fix intermittent build failures
      sudo apt --assume-yes install mir-demos mir-graphics-drivers-desktop
      snapcraftctl pull

  mir:
    after: [ppa-mir-release]
    plugin: nil
    stage-packages:
      - mir-graphics-drivers-desktop
      - mir-demos
      - libgl1-mesa-dri
    prime:
      - -lib/udev
      - -usr/doc
      - -usr/doc-base
      - -usr/share/applications
      - -usr/share/apport
      - -usr/share/bug
      - -usr/share/doc
      - -usr/share/doc-base
      - -usr/share/icons
      - -usr/share/libdrm
      - -usr/share/libwacom
      - -usr/share/lintian
      - -usr/share/man
      - -usr/share/pkgconfig
      - -usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/mir/server-platform/server-mesa-x11.so.*
      - -usr/bin/miral-app
      - -usr/bin/miral-desktop
      - -usr/bin/miral-run
      - -usr/bin/miral-shell
      - -usr/bin/miral-xrun

  icons:
    plugin: nil
    stage-packages: [dmz-cursor-theme]

  glue:
    plugin: dump
    source: glue
