name: mir-kiosk
version: mir
version-script: |
    LANG=C apt-cache policy mir-demos | sed -rne 's/^\s+Candidate:\s+(.*)-[^-]+$/\1/p'
summary: A minimal Mir based shell for kiosk type applications
description: A minimal Mir based shell for kiosk type applications
confinement: strict
grade: stable
base: core18

slots:
  mir-libs-1604:
    interface: content
    content: mir0-1604
    read: [usr/lib]

apps:
  mir-kiosk:
    command: bin/run-miral
    daemon: simple
    slots:
      - mir
      - wayland
    plugs:
      - opengl
    environment:
      XKB_CONFIG_ROOT: $SNAP/usr/share/X11/xkb
      XDG_CONFIG_HOME: $SNAP_DATA
      XCURSOR_PATH:    $SNAP/icons
      __EGL_VENDOR_LIBRARY_DIRS: $SNAP/etc/glvnd/egl_vendor.d:$SNAP/usr/share/glvnd/egl_vendor.d

parts:
  mir:
    plugin: nil
    stage-packages:
      - mir-graphics-drivers-desktop
      - mir-demos

  mesa:
    plugin: nil
    stage-packages:
      - libgl1-mesa-dri

  icons:
    plugin: nil
    stage-packages: [dmz-cursor-theme]
    organize:
      usr/share/icons/DMZ-White: icons/default
    prime:
     - icons/default

  glue:
    plugin: dump
    source: glue
