name: mir-kiosk
version: 0.1
summary: A minimal Mir based shell for kiosk type applications
description: A minimal Mir based shell for kiosk type applications
confinement: strict
grade: devel

plugs:
  mir-libs:
    interface: content
    content: mir-libs
    target: mir-libs
    default-provider: mir-libs

apps:
  mir-kiosk:
    command: bin/run-miral
    daemon: simple
    slots: [mir]
    plugs:
      - opengl
      - mir-libs

parts:
  miral-examples:
    plugin: nil
    stage-packages:
     - miral-examples
    build-attributes:
     - no-system-libraries
    prime:
      - usr/lib
      - -usr/lib/*/libmir* #Use the libraries from mir-libs content plug
      - usr/bin/miral-kiosk
      - usr/bin/miral-shell
      - usr/share/X11/xkb

  icons:
    plugin: nil
    stage-packages: [dmz-cursor-theme]
    organize:
      usr/share/icons/DMZ-White: icons/default
    prime:
     - icons/default

  glue:
    plugin: dump
    source: glue

  inotify-tools:
    plugin: nil
    stage-packages: [inotify-tools]
    prime:
     - usr/bin/inotifywait
     - usr/lib
